### PR TITLE
Disable curl via cmake

### PR DESCRIPTION
**Pull request by lladdy**
- Provide the option to disable curl via setting the cmake option: DISABLE_CURL=ON.
- Avoid including the curl header when DISABLE_CURL is defined - not sure this is really needed, but it seemed cleaner.

### CODE REVIEW

**Comment by alkurbatov** [comment]
a. Why not to call the new option: Enable replays upload? i.e. to make it independant from the underlying technology? Also additional ‘not’ will not be needed.
b. The curl functionality should be moved to a separate file to reduce number of ifdefs.

**Comment by alkurbatov** [comment]
Also it looks like the current build is broken, because you actually disable only curl.h. What about the calls to the curl functions in UploadMime and LoginToServer?

**Comment by Archiatrus** [comment]
Just a thought: since it is "recommended for most users" to disable the replay upload, why not make it the default?

**Comment by Cryptyc** [comment]
@alkurbatov The current define is already in there that disables the actual function, I just hadn't added it to the header file, so this should work fine.  I think moving it to a seperate file might be an option though.

**Comment by alkurbatov** [comment]
@Cryptyc @lladdy 
True, sorry, my mistake.

**Comment by lladdy** [comment]
> Why not to call the new option: Enable replays upload? i.e. to make it independent from the underlying technology? Also additional ‘not’ will not be needed.

My initial intention was to quickly make it easy to disable the need for CMake to find curl when DISABLE_CURL is set (I was setting up a new machine at the time and didn't want to have to download curl).
Your suggestion (or something like it) is probably the better option though.
To me it's mostly a question of whether it's done in this PR.
@Cryptyc @Archiatrus @alkurbatov Thoughts?

> Just a thought: since it is "recommended for most users" to disable the replay upload, why not make it the default?

After thinking it through, I think I will do this.

**Comment by lladdy** [comment]
> After thinking it through, I think I will do this.

I might be being paranoid, but what are the chances of us setting the default DISABLE_CURL to ON and the ladder accidentally being run without curl in the future and therefore not uploading replays?
Currently I don't believe there is any mechanic to stop this happening if we set it to default on?

**Comment by Archiatrus** [comment]
Put a big warning [here](https://github.com/Cryptyc/Sc2LadderServer/blob/864fc10416336e3ccae5a0a8cc2c45a631aae1e6/src/sc2ladderserver/main.cpp#L12). And if that doesn't help, I think people will notice pretty quickly and say something.

**Comment by alkurbatov** [comment]
Regarding the renaming: imho, it should be done in this PR.

>Currently I don't believe there is any mechanic to stop this happening if we set it to default on?

It is a tradeoff.
On the one hand we have @Cryptyc who really need to upload the replays. Probably there are more people but not many.
On the other hand, it just works for all the other users.

If you will keep it OFF by default, we have to document how to set it, how to clean up the cmake's cache etc.

**Comment by Cryptyc** [comment]
I think it makes sense to have it turned off by default.  Most people will benefit from that.  It won't be that hard for me to turn it on, so I really don't mind.

Makes more sense to do it in this PR than to set up a new one

**Comment by lladdy** [comment]
Updates pushed.
Let me know if I missed anything.

- Default DISABLE_CURL to ON
- Throw exception when DISABLE_CURL is set to ON and the LadderManager configuration conflicts with this.
- Other more minor changes

Regarding renaming DISABLE_CURL:
The pertinent function currently is only to disable curl during the build - disabling replay upload can be done in the configuration.
I feel if we were to rename it, we might be better served by taking a slightly more generic approach i.e. something roughly like "DISABLE_WEB_API_SUPPORT".
As the ladder manager becomes more integrated with the web API, this might see more relevance.
I'm open to more discussion regarding this but I'd rather address it separate to this PR if that works for you guys.

**Comment by alkurbatov** [comment]
By naming the variable in that way you emphasize the underlying technology and not the functionality.
There are two cons:
a. If we drop curl someday, we have to rename the variable again, i.e. do additional work.
b. For a person not really knowing the internals disable curl means nothing while disable_replays_upload or even standalone_server makes more sense. The config variable can be removed to avoid confusion.

I don’t see why the renaming should be postponed.

**Comment by alkurbatov** [comment]
Also 
if Enable_curl == On
is better
then
if Disable_Curl != On

Simpler to read.

**Comment by lladdy** [comment]
My intention with this command was only to disable curl so it wasn't linked into the build.
The way I see it, the functionality of `DISABLE_CURL` can be viewed as relevant to **building** the ladder - hence it's in the **build** system, as opposed to functionality which dictates how the ladder operates at **runtime** - found in the **runtime configuration**.
I feel in the context of **building** the ladder "emphasize the underlying technology" is not as relevant a statement. At the build stage, I'm not sure the libraries/etc are really "underlying" anymore.

With that said, I would still be comfortable renaming it, but I don't think we could simply just rename it to something like `DISABLE_REPLAY_UPLOAD` as this doesn't cover its functionality.
Currently there are two configuration settings I know of that deal with curl usage:
`EnableReplayUpload`
`EnableServerLogin`
I expect there will soon be other functionality that deals with the website as well.
Something like `disable_replays_upload` would only cover one of the uses.
I agree that `standalone_server` makes more sense.

> Also
> if Enable_curl == On
> is better
> then
> if Disable_Curl != On
> 
> Simpler to read.

I agree here, though I preferred at the time to keep it the same as the preprocessor directive for clarity. if we change one it might be good to also change the other to match.

**Comment by Cryptyc** [comment]
I think ENABLE_CURL is fine here.  It should be obvious to people who want to build, what this means.  We can change it if we ever want to change the library we can look at it again.  If we keep it as default off, then most people can just ignore it.

**Pull request merged**
